//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ResourceID { get; set; }
        public int TeamMemberID { get; set; }
        public Nullable<decimal> PercentageCompleted { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string HelpDesk_Number1 { get; set; }
        public string HelpDesk_Number2 { get; set; }
        public string HelpDesk_Number3 { get; set; }
        public string HelpDesk_Number4 { get; set; }
        public string HelpDesk_Number5 { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}
